FROM quay.io/jupyter/base-notebook
WORKDIR /home/jovyan/work
COPY . .
RUN pip install --no-cache-dir -r requirements.txt && \
    pip install -e .
EXPOSE 8888
ENV JUPYTER_ENABLE_LAB=yes
RUN echo "tattoosarefun" | jupyter notebook password
CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"] 